/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiUserMessage {
  id: number
  other: string
  message: Array<number>
  sentByOther: boolean
}
export interface NapiGroupMessage {
  id: number
  groupId: number
  by: string
  message: Array<number>
  channelId: number
  epoch: number
}
export interface NapiCallSignal {
  callId: number
  senderUsername: string
  receiverUsername: string
  signalType: number
  sdp: string
  candidate: string
  sdpMLineIndex: number
  sdpMid: string
  senderDeviceId: number
}
export interface NapiGroupMeetingSignal {
  groupId: number
  channelId: number
  sessionId: number
  signalType: number
  username: string
  cfMeetingId: string
}
export interface NapiConversation {
  other: string
  settings: number
}
export interface NapiGroupInfo {
  id: number
  name: string
  description: string
  pending: boolean
  owner: string
  hasLocalState: boolean
}
export interface NapiGroupInfoDb {
  id: number
  name: string
  description: string
}
export interface NapiUpdateUserProposal {
  username: string
  roleId: number
}
export interface NapiUpdateRoleProposal {
  name: string
  roleId: number
  permissions: number
  delete: boolean
  color: number
}
export declare function initLogger(filePath: string): void
export declare class FireflyClientNode {
  static create(fireflyBaseUrl: string, fireflyBaseWsUrl: string, retryIntervalInMs: number, callbacksObj: object, keyStoresPathname: string, requestTimeoutInMs: number): object
  setAccessToken(token: string): void
  initializeWithRetrying(): Promise<void>
  checkSetup(): Promise<void>
  dispose(): Promise<void>
  encryptAndSend(to: string, payload: Array<number>): Promise<NapiUserMessage>
  uploadFcmToken(token?: string | undefined | null): Promise<void>
  getConnectionState(): string
  isInitialized(): boolean
  getConversations(token: string): Promise<Array<NapiConversation>>
  createGroup(name: string, description: string): Promise<NapiGroupInfoDb>
  encryptAndSendGroup(groupId: number, payload: Array<number>): Promise<number>
  getGroupExtension(groupId: number): Promise<Array<number>>
  exportGroupMeetingKey(groupId: number): Promise<Array<number>>
  loadAllGroups(): Promise<void>
  updateGroupUsers(groupId: number, users: Array<NapiUpdateUserProposal>): Promise<number>
  updateGroupChannel(groupId: number, id: number, isDelete: boolean, name: string, channelTy: number, defaultPermissions: number): Promise<number>
  updateGroupRoles(groupId: number, roles: Array<NapiUpdateRoleProposal>): Promise<number>
  updateGroupRolesInChannel(groupId: number, channelId: number, roles: Array<NapiUpdateRoleProposal>): Promise<number>
  addGroupMember(groupId: number, username: string, roleId: number): Promise<void>
  kickGroupMember(groupId: number, username: string): Promise<void>
  deleteGroup(groupId: number): Promise<void>
  createJoinLink(groupId: number, expiresInSeconds: number, maxUses: number): Promise<string>
  joinViaLink(token: string): Promise<void>
  generateCallId(): number
  initiateCall(callId: number, receiverUsername: string, sdpOffer: string): Promise<void>
  acceptCall(callId: number, callerUsername: string, sdpAnswer: string): Promise<void>
  rejectCall(callId: number, callerUsername: string): Promise<void>
  cancelCall(callId: number, receiverUsername: string): Promise<void>
  hangupCall(callId: number, otherUsername: string): Promise<void>
  sendIceCandidate(callId: number, otherUsername: string, candidate: string, sdpMid: string, sdpMLineIndex: number): Promise<void>
  getGroupInfos(): Promise<Array<NapiGroupInfo>>
  getGroupMessages(groupId: number, startBefore: number, limit: number): Promise<Array<NapiGroupMessage>>
  getOnlineStatus(usernames: Array<string>): Promise<Array<string>>
}
